"""
" author Meisze Wong
"        www.linkedin.com/pub/macy-wong/46/550/37b/
"        github.com/mwong510ca/Boggle_TrieDataStructure
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appGame_Final.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from gui.customTileLabel import ImageLabel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 450)
        MainWindow.setMinimumSize(QtCore.QSize(720, 450))
        MainWindow.setSizeIncrement(QtCore.QSize(1, 10))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutMain = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayoutMain.setObjectName("gridLayoutMain")

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        
        self.puzzleLayout = QtWidgets.QGridLayout()
        self.puzzleLayout.setObjectName("puzzleLayout")
        self.puzzleSetup = QtWidgets.QLabel(self.centralwidget)
        self.puzzleSetup.setSizePolicy(sizePolicy)
        self.puzzleSetup.setMinimumSize(QtCore.QSize(300, 30))
        self.puzzleSetup.setMaximumSize(QtCore.QSize(16777215, 50))
        self.puzzleSetup.setSizeIncrement(QtCore.QSize(0, 1))
        self.puzzleSetup.setAlignment(QtCore.Qt.AlignCenter)
        self.puzzleSetup.setObjectName("puzzleSetup")
        self.puzzleLayout.addWidget(self.puzzleSetup, 0, 0, 1, 2)
        self.puzzleLevel = QtWidgets.QComboBox(self.centralwidget)
        self.puzzleLevel.setSizePolicy(sizePolicy)
        self.puzzleLevel.setMinimumSize(QtCore.QSize(0, 40))
        self.puzzleLevel.setSizeIncrement(QtCore.QSize(0, 2))
        self.puzzleLevel.setObjectName("puzzleLevel")
        self.puzzleLevel.addItem("")
        self.puzzleLevel.addItem("")
        self.puzzleLevel.addItem("")
        self.puzzleLevel.addItem("")
        self.puzzleLevel.addItem("")
        self.puzzleLayout.addWidget(self.puzzleLevel, 1, 0, 1, 1)
        self.puzzleGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.puzzleGenerate.setSizePolicy(sizePolicy)
        self.puzzleGenerate.setMinimumSize(QtCore.QSize(0, 40))
        self.puzzleGenerate.setMaximumSize(QtCore.QSize(16777215, 50))
        self.puzzleGenerate.setSizeIncrement(QtCore.QSize(0, 2))
        self.puzzleGenerate.setObjectName("puzzleGenerate")
        self.puzzleLayout.addWidget(self.puzzleGenerate, 2, 0, 1, 1)
        self.puzzlePlay = QtWidgets.QPushButton(self.centralwidget)
        self.puzzlePlay.setSizePolicy(sizePolicy)
        self.puzzlePlay.setMinimumSize(QtCore.QSize(0, 40))
        self.puzzlePlay.setMaximumSize(QtCore.QSize(16777215, 50))
        self.puzzlePlay.setSizeIncrement(QtCore.QSize(0, 2))
        self.puzzlePlay.setObjectName("puzzlePlay")
        self.puzzleLayout.addWidget(self.puzzlePlay, 2, 1, 1, 1)
        self.puzzleNew = QtWidgets.QPushButton(self.centralwidget)
        self.puzzleNew.setSizePolicy(sizePolicy)
        self.puzzleNew.setMinimumSize(QtCore.QSize(0, 40))
        self.puzzleNew.setMaximumSize(QtCore.QSize(16777215, 50))
        self.puzzleNew.setSizeIncrement(QtCore.QSize(0, 2))
        self.puzzleNew.setObjectName("puzzleNew")
        self.puzzleLayout.addWidget(self.puzzleNew, 1, 1, 1, 1)
        self.gridLayoutMain.addLayout(self.puzzleLayout, 0, 0, 1, 1)

        tileFont = QtGui.QFont()
        tileFont.setFamily("Arial Black")
        tileFont.setPointSize(16)

        self.boardLayout = QtWidgets.QGridLayout()
        self.boardLayout.setSpacing(0)
        self.boardLayout.setObjectName("boardLayout")
        self.tile0 = ImageLabel(self.centralwidget)
        self.tile0.setMinimumSize(QtCore.QSize(40, 40))
        self.tile0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile0.setFont(tileFont)
        self.tile0.setMouseTracking(True)
        self.tile0.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile0.setPixmap(QtGui.QPixmap("images/panda_1.png"))
        self.tile0.setScaledContents(True)
        self.tile0.setAlignment(QtCore.Qt.AlignCenter)
        self.tile0.setMargin(1)
        self.tile0.setObjectName("tile0")
        self.boardLayout.addWidget(self.tile0, 0, 0, 1, 1)
        self.tile1 = ImageLabel(self.centralwidget)
        self.tile1.setMinimumSize(QtCore.QSize(40, 40))
        self.tile1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile1.setFont(tileFont)
        self.tile1.setMouseTracking(True)
        self.tile1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile1.setPixmap(QtGui.QPixmap("images/panda_2.png"))
        self.tile1.setScaledContents(True)
        self.tile1.setAlignment(QtCore.Qt.AlignCenter)
        self.tile1.setMargin(1)
        self.tile1.setObjectName("tile1")
        self.boardLayout.addWidget(self.tile1, 0, 1, 1, 1)
        self.tile2 = ImageLabel(self.centralwidget)
        self.tile2.setMinimumSize(QtCore.QSize(40, 40))
        self.tile2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile2.setFont(tileFont)
        self.tile2.setMouseTracking(True)
        self.tile2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile2.setPixmap(QtGui.QPixmap("images/panda_3.png"))
        self.tile2.setScaledContents(True)
        self.tile2.setAlignment(QtCore.Qt.AlignCenter)
        self.tile2.setMargin(1)
        self.tile2.setObjectName("tile2")
        self.boardLayout.addWidget(self.tile2, 0, 2, 1, 1)
        self.tile3 = ImageLabel(self.centralwidget)
        self.tile3.setMinimumSize(QtCore.QSize(40, 40))
        self.tile3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile3.setFont(tileFont)
        self.tile3.setMouseTracking(True)
        self.tile3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile3.setPixmap(QtGui.QPixmap("images/panda_4.png"))
        self.tile3.setScaledContents(True)
        self.tile3.setAlignment(QtCore.Qt.AlignCenter)
        self.tile3.setMargin(1)
        self.tile3.setObjectName("tile3")
        self.boardLayout.addWidget(self.tile3, 0, 3, 1, 1)
        self.tile4 = ImageLabel(self.centralwidget)
        self.tile4.setMinimumSize(QtCore.QSize(40, 40))
        self.tile4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile4.setFont(tileFont)
        self.tile4.setMouseTracking(True)
        self.tile4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile4.setPixmap(QtGui.QPixmap("images/panda_5.png"))
        self.tile4.setScaledContents(True)
        self.tile4.setAlignment(QtCore.Qt.AlignCenter)
        self.tile4.setMargin(1)
        self.tile4.setObjectName("tile4")
        self.boardLayout.addWidget(self.tile4, 1, 0, 1, 1)
        self.tile5 = ImageLabel(self.centralwidget)
        self.tile5.setMinimumSize(QtCore.QSize(40, 40))
        self.tile5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile5.setFont(tileFont)
        self.tile5.setMouseTracking(True)
        self.tile5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile5.setPixmap(QtGui.QPixmap("images/panda_6.png"))
        self.tile5.setScaledContents(True)
        self.tile5.setAlignment(QtCore.Qt.AlignCenter)
        self.tile5.setMargin(1)
        self.tile5.setObjectName("tile5")
        self.boardLayout.addWidget(self.tile5, 1, 1, 1, 1)
        self.tile6 = ImageLabel(self.centralwidget)
        self.tile6.setMinimumSize(QtCore.QSize(40, 40))
        self.tile6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile6.setFont(tileFont)
        self.tile6.setMouseTracking(True)
        self.tile6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile6.setPixmap(QtGui.QPixmap("images/panda_7.png"))
        self.tile6.setScaledContents(True)
        self.tile6.setAlignment(QtCore.Qt.AlignCenter)
        self.tile6.setMargin(1)
        self.tile6.setObjectName("tile6")
        self.boardLayout.addWidget(self.tile6, 1, 2, 1, 1)
        self.tile7 = ImageLabel(self.centralwidget)
        self.tile7.setMinimumSize(QtCore.QSize(40, 40))
        self.tile7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile7.setFont(tileFont)
        self.tile7.setMouseTracking(True)
        self.tile7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile7.setPixmap(QtGui.QPixmap("images/panda_8.png"))
        self.tile7.setScaledContents(True)
        self.tile7.setAlignment(QtCore.Qt.AlignCenter)
        self.tile7.setMargin(1)
        self.tile7.setObjectName("tile7")
        self.boardLayout.addWidget(self.tile7, 1, 3, 1, 1)
        self.tile8 = ImageLabel(self.centralwidget)
        self.tile8.setMinimumSize(QtCore.QSize(40, 40))
        self.tile8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile8.setFont(tileFont)
        self.tile8.setMouseTracking(True)
        self.tile8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile8.setPixmap(QtGui.QPixmap("images/panda_9.png"))
        self.tile8.setScaledContents(True)
        self.tile8.setAlignment(QtCore.Qt.AlignCenter)
        self.tile8.setMargin(1)
        self.tile8.setObjectName("tile8")
        self.boardLayout.addWidget(self.tile8, 2, 0, 1, 1)
        self.tile9 = ImageLabel(self.centralwidget)
        self.tile9.setMinimumSize(QtCore.QSize(40, 40))
        self.tile9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile9.setFont(tileFont)
        self.tile9.setMouseTracking(True)
        self.tile9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile9.setPixmap(QtGui.QPixmap("images/panda_10.png"))
        self.tile9.setScaledContents(True)
        self.tile9.setAlignment(QtCore.Qt.AlignCenter)
        self.tile9.setMargin(1)
        self.tile9.setObjectName("tile9")
        self.boardLayout.addWidget(self.tile9, 2, 1, 1, 1)
        self.tile10 = ImageLabel(self.centralwidget)
        self.tile10.setMinimumSize(QtCore.QSize(40, 40))
        self.tile10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile10.setFont(tileFont)
        self.tile10.setMouseTracking(True)
        self.tile10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile10.setPixmap(QtGui.QPixmap("images/panda_11.png"))
        self.tile10.setScaledContents(True)
        self.tile10.setAlignment(QtCore.Qt.AlignCenter)
        self.tile10.setMargin(1)
        self.tile10.setObjectName("tile10")
        self.boardLayout.addWidget(self.tile10, 2, 2, 1, 1)
        self.tile11 = ImageLabel(self.centralwidget)
        self.tile11.setMinimumSize(QtCore.QSize(40, 40))
        self.tile11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile11.setFont(tileFont)
        self.tile11.setMouseTracking(True)
        self.tile11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile11.setPixmap(QtGui.QPixmap("images/panda_12.png"))
        self.tile11.setScaledContents(True)
        self.tile11.setAlignment(QtCore.Qt.AlignCenter)
        self.tile11.setMargin(1)
        self.tile11.setObjectName("tile11")
        self.boardLayout.addWidget(self.tile11, 2, 3, 1, 1)
        self.tile12 = ImageLabel(self.centralwidget)
        self.tile12.setMinimumSize(QtCore.QSize(40, 40))
        self.tile12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile12.setFont(tileFont)
        self.tile12.setMouseTracking(True)
        self.tile12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile12.setPixmap(QtGui.QPixmap("images/panda_13.png"))
        self.tile12.setScaledContents(True)
        self.tile12.setAlignment(QtCore.Qt.AlignCenter)
        self.tile12.setMargin(1)
        self.tile12.setObjectName("tile12")
        self.boardLayout.addWidget(self.tile12, 3, 0, 1, 1)
        self.tile13 = ImageLabel(self.centralwidget)
        self.tile13.setMinimumSize(QtCore.QSize(40, 40))
        self.tile13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile13.setFont(tileFont)
        self.tile13.setMouseTracking(True)
        self.tile13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile13.setPixmap(QtGui.QPixmap("images/panda_14.png"))
        self.tile13.setScaledContents(True)
        self.tile13.setAlignment(QtCore.Qt.AlignCenter)
        self.tile13.setMargin(1)
        self.tile13.setObjectName("tile13")
        self.boardLayout.addWidget(self.tile13, 3, 1, 1, 1)
        self.tile14 = ImageLabel(self.centralwidget)
        self.tile14.setMinimumSize(QtCore.QSize(40, 40))
        self.tile14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile14.setFont(tileFont)
        self.tile14.setMouseTracking(True)
        self.tile14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile14.setPixmap(QtGui.QPixmap("images/panda_15.png"))
        self.tile14.setScaledContents(True)
        self.tile14.setAlignment(QtCore.Qt.AlignCenter)
        self.tile14.setMargin(1)
        self.tile14.setObjectName("tile14")
        self.boardLayout.addWidget(self.tile14, 3, 2, 1, 1)
        self.tile15 = ImageLabel(self.centralwidget)
        self.tile15.setMinimumSize(QtCore.QSize(40, 40))
        self.tile15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tile15.setFont(tileFont)
        self.tile15.setMouseTracking(True)
        self.tile15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tile15.setPixmap(QtGui.QPixmap("images/panda_space.png"))
        self.tile15.setScaledContents(True)
        self.tile15.setAlignment(QtCore.Qt.AlignCenter)
        self.tile15.setMargin(1)
        self.tile15.setObjectName("tile15")
        self.boardLayout.addWidget(self.tile15, 3, 3, 1, 1)
        self.gridLayoutMain.addLayout(self.boardLayout, 1, 0, 2, 1)

        headerFont = QtGui.QFont()
        headerFont.setPointSize(14)
        headerFont.setBold(True)
        headerFont.setItalic(True)
        headerFont.setWeight(75)

        self.displayLayout = QtWidgets.QGridLayout()
        self.displayLayout.setContentsMargins(0, -1, -1, -1)
        self.displayLayout.setObjectName("displayLayout")
        self.gameHeader = QtWidgets.QLabel(self.centralwidget)
        self.gameHeader.setMinimumSize(QtCore.QSize(100, 30))
        self.gameHeader.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gameHeader.setSizeIncrement(QtCore.QSize(0, 0))
        self.gameHeader.setFont(headerFont)
        self.gameHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.gameHeader.setObjectName("gameHeader")
        self.displayLayout.addWidget(self.gameHeader, 0, 0, 1, 1)
        self.gameCounter = QtWidgets.QLabel(self.centralwidget)
        self.gameCounter.setMinimumSize(QtCore.QSize(0, 30))
        self.gameCounter.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gameCounter.setSizeIncrement(QtCore.QSize(0, 0))
        self.gameCounter.setObjectName("gameCounter")
        self.displayLayout.addWidget(self.gameCounter, 0, 1, 1, 1)
        self.gameTime = QtWidgets.QLabel(self.centralwidget)
        self.gameTime.setMinimumSize(QtCore.QSize(0, 30))
        self.gameTime.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gameTime.setSizeIncrement(QtCore.QSize(0, 0))
        self.gameTime.setObjectName("gameTime")
        self.displayLayout.addWidget(self.gameTime, 0, 2, 1, 1)
        self.gameBackward = QtWidgets.QPushButton(self.centralwidget)
        self.gameBackward.setSizePolicy(sizePolicy)
        self.gameBackward.setMinimumSize(QtCore.QSize(0, 40))
        self.gameBackward.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gameBackward.setSizeIncrement(QtCore.QSize(0, 0))
        self.gameBackward.setObjectName("gameBackward")
        self.displayLayout.addWidget(self.gameBackward, 1, 1, 1, 1)
        self.gameReset = QtWidgets.QPushButton(self.centralwidget)
        self.gameReset.setSizePolicy(sizePolicy)
        self.gameReset.setMinimumSize(QtCore.QSize(0, 40))
        self.gameReset.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gameReset.setSizeIncrement(QtCore.QSize(0, 0))
        self.gameReset.setObjectName("gameReset")
        self.displayLayout.addWidget(self.gameReset, 1, 2, 1, 1)
        self.gameLine = QtWidgets.QFrame(self.centralwidget)
        self.gameLine.setSizePolicy(sizePolicy)
        self.gameLine.setSizeIncrement(QtCore.QSize(0, 1))
        self.gameLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.gameLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gameLine.setObjectName("gameLine")
        self.displayLayout.addWidget(self.gameLine, 2, 0, 1, 3)
        
        self.solverHeader = QtWidgets.QLabel(self.centralwidget)
        self.solverHeader.setMinimumSize(QtCore.QSize(100, 30))
        self.solverHeader.setMaximumSize(QtCore.QSize(16777215, 50))
        self.solverHeader.setSizeIncrement(QtCore.QSize(0, 0))
        self.solverHeader.setFont(headerFont)
        self.solverHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.solverHeader.setObjectName("solverHeader")
        self.displayLayout.addWidget(self.solverHeader, 3, 0, 1, 1)
        self.solverVersion = QtWidgets.QButtonGroup(self)
        self.solverVersion.setObjectName("solverVersion")
        self.solverStandard = QtWidgets.QRadioButton(self.centralwidget)
        self.solverStandard.setSizePolicy(sizePolicy)
        self.solverStandard.setMinimumSize(QtCore.QSize(0, 30))
        self.solverStandard.setMaximumSize(QtCore.QSize(16777215, 50))
        self.solverStandard.setSizeIncrement(QtCore.QSize(0, 0))
        self.solverStandard.setObjectName("solverStandard")
        self.solverVersion.addButton(self.solverStandard)
        self.displayLayout.addWidget(self.solverStandard, 3, 1, 1, 1)
        self.solverAdvanced = QtWidgets.QRadioButton(self.centralwidget)
        self.solverAdvanced.setSizePolicy(sizePolicy)
        self.solverAdvanced.setMinimumSize(QtCore.QSize(100, 30))
        self.solverAdvanced.setMaximumSize(QtCore.QSize(16777215, 50))
        self.solverAdvanced.setSizeIncrement(QtCore.QSize(0, 0))
        self.solverAdvanced.setChecked(True)
        self.solverAdvanced.setObjectName("solverAdvanced")
        self.solverVersion.addButton(self.solverAdvanced)
        self.displayLayout.addWidget(self.solverAdvanced, 3, 2, 1, 1)
        self.solverHeuristic = QtWidgets.QComboBox(self.centralwidget)
        self.solverHeuristic.setSizePolicy(sizePolicy)
        self.solverHeuristic.setMinimumSize(QtCore.QSize(0, 30))
        self.solverHeuristic.setMaximumSize(QtCore.QSize(16777215, 50))
        self.solverHeuristic.setSizeIncrement(QtCore.QSize(0, 0))
        self.solverHeuristic.setObjectName("solverHeuristic")
        self.solverHeuristic.addItem("")
        self.solverHeuristic.addItem("")
        self.solverHeuristic.addItem("")
        self.solverHeuristic.addItem("")
        self.solverHeuristic.addItem("")
        self.solverHeuristic.addItem("")
        self.solverHeuristic.addItem("")
        self.displayLayout.addWidget(self.solverHeuristic, 4, 1, 1, 2)
        self.solverSearchNow = QtWidgets.QPushButton(self.centralwidget)
        self.solverSearchNow.setSizePolicy(sizePolicy)
        self.solverSearchNow.setMinimumSize(QtCore.QSize(0, 40))
        self.solverSearchNow.setMaximumSize(QtCore.QSize(16777215, 50))
        self.solverSearchNow.setSizeIncrement(QtCore.QSize(0, 0))
        self.solverSearchNow.setObjectName("solverSearchNow")
        self.displayLayout.addWidget(self.solverSearchNow, 5, 1, 1, 2)
        self.solverEstimate = QtWidgets.QLabel(self.centralwidget)
        self.solverEstimate.setMinimumSize(QtCore.QSize(100, 30))
        self.solverEstimate.setMaximumSize(QtCore.QSize(16777215, 50))
        self.solverEstimate.setSizeIncrement(QtCore.QSize(0, 0))
        self.solverEstimate.setObjectName("solverEstimate")
        self.displayLayout.addWidget(self.solverEstimate, 5, 0, 1, 1)
        self.solverResult = QtWidgets.QLabel(self.centralwidget)
        self.solverResult.setMinimumSize(QtCore.QSize(150, 30))
        self.solverResult.setMaximumSize(QtCore.QSize(16777215, 50))
        self.solverResult.setSizeIncrement(QtCore.QSize(0, 0))
        self.solverResult.setObjectName("solverResult")
        self.displayLayout.addWidget(self.solverResult, 6, 0, 1, 1)
        self.solverNodes = QtWidgets.QLabel(self.centralwidget)
        self.solverNodes.setMinimumSize(QtCore.QSize(0, 30))
        self.solverNodes.setMaximumSize(QtCore.QSize(16777215, 50))
        self.solverNodes.setSizeIncrement(QtCore.QSize(0, 0))
        self.solverNodes.setObjectName("solverNodes")
        self.displayLayout.addWidget(self.solverNodes, 6, 1, 1, 1)
        self.solverTime = QtWidgets.QLabel(self.centralwidget)
        self.solverTime.setMinimumSize(QtCore.QSize(0, 30))
        self.solverTime.setMaximumSize(QtCore.QSize(16777215, 50))
        self.solverTime.setSizeIncrement(QtCore.QSize(0, 0))
        self.solverTime.setObjectName("solverTime")
        self.displayLayout.addWidget(self.solverTime, 6, 2, 1, 1)
        self.solverLine = QtWidgets.QFrame(self.centralwidget)
        self.solverLine.setSizePolicy(sizePolicy)
        self.solverLine.setSizeIncrement(QtCore.QSize(0, 1))
        self.solverLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.solverLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.solverLine.setObjectName("solverLine")
        self.displayLayout.addWidget(self.solverLine, 7, 0, 1, 3)
        self.gridLayoutMain.addLayout(self.displayLayout, 0, 1, 2, 1)

        self.statusLayout = QtWidgets.QGridLayout()
        self.statusLayout.setContentsMargins(0, -1, -1, -1)
        self.statusLayout.setObjectName("statusLayout")
        self.informationDetails = QtWidgets.QTextBrowser(self.centralwidget)
        self.informationDetails.setSizePolicy(sizePolicy)
        self.informationDetails.setMinimumSize(QtCore.QSize(380, 0))
        self.informationDetails.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.informationDetails.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.informationDetails.setFont(font)
        self.informationDetails.setObjectName("informationDetails")
        self.statusLayout.addWidget(self.informationDetails, 8, 0, 1, 3)
        self.gridLayoutMain.addLayout(self.statusLayout, 2, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menuMain = QtWidgets.QMenuBar(MainWindow)
        self.menuMain.setGeometry(QtCore.QRect(0, 0, 720, 22))
        self.menuMain.setNativeMenuBar(False)
        self.menuMain.setObjectName("menuMain")
        self.menuFile = QtWidgets.QMenu(self.menuMain)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menuMain)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menuMain)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuMain)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout15Puzzle = QtWidgets.QAction(MainWindow)
        self.actionAbout15Puzzle.setObjectName("actionAbout15Puzzle")
        self.actionAboutAuthor = QtWidgets.QAction(MainWindow)
        self.actionAboutAuthor.setObjectName("actionAboutAuthor")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNumbers = QtWidgets.QAction(MainWindow)
        self.actionNumbers.setObjectName("actionNumbers")
        self.actionPandaBabies = QtWidgets.QAction(MainWindow)
        self.actionPandaBabies.setObjectName("actionPandaBabies")
        self.actionCustomImage = QtWidgets.QAction(MainWindow)
        self.actionCustomImage.setObjectName("actionCustomImage")
        self.actionTimeoutLimit = QtWidgets.QAction(MainWindow)
        self.actionTimeoutLimit.setObjectName("actionTimeoutLimit")
        self.actionAutoMoveSpeed = QtWidgets.QAction(MainWindow)
        self.actionAutoMoveSpeed.setObjectName("actionAutoMoveSpeed")
        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")

        self.menuFile.addAction(self.actionAbout15Puzzle)
        self.menuFile.addAction(self.actionAboutAuthor)
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionNumbers)
        self.menuSettings.addAction(self.actionPandaBabies)
        self.menuSettings.addAction(self.actionCustomImage)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionTimeoutLimit)
        self.menuSettings.addAction(self.actionAutoMoveSpeed)
        self.menuHelp.addAction(self.actionInstructions)
        self.menuMain.addAction(self.menuFile.menuAction())
        self.menuMain.addAction(self.menuSettings.menuAction())
        self.menuMain.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout15Puzzle.setText(_translate("MainWindow", "About 15 Puzzle"))
        self.actionAboutAuthor.setText(_translate("MainWindow", "About Author"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionNumbers.setText(_translate("MainWindow", "Numbers"))
        self.actionPandaBabies.setText(_translate("MainWindow", "Panda Babies"))
        self.actionCustomImage.setText(_translate("MainWindow", "Custom Image"))
        self.actionTimeoutLimit.setText(_translate("MainWindow", "Timeout Limit"))
        self.actionAutoMoveSpeed.setText(_translate("MainWindow", "Auto Move Speed"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))
        
        self.puzzleSetup.setText(_translate("MainWindow", "Click 2 tiles to swap or generate new puzzle:"))
        self.puzzleLevel.setItemText(0, _translate("MainWindow", "Goal State"))
        self.puzzleLevel.setItemText(1, _translate("MainWindow", "Random"))
        self.puzzleLevel.setItemText(2, _translate("MainWindow", "Easy  (6-25 moves)"))
        self.puzzleLevel.setItemText(3, _translate("MainWindow", "Moderate  (26-50 moves)"))
        self.puzzleLevel.setItemText(4, _translate("MainWindow", "Hard  (50+ moves)"))
        self.puzzleLevel.setCurrentIndex(1)
        self.puzzleGenerate.setText(_translate("MainWindow", "Generate"))
        self.puzzlePlay.setText(_translate("MainWindow", "Play"))
        self.puzzleNew.setText(_translate("MainWindow", "New"))

        self.gameHeader.setText(_translate("MainWindow", "Game"))
        self.gameCounter.setText(_translate("MainWindow", "Count:"))
        self.gameTime.setText(_translate("MainWindow", "Time:"))
        self.gameBackward.setText(_translate("MainWindow", "Go Back"))
        self.gameReset.setText(_translate("MainWindow", "Reset"))

        self.solverHeader.setText(_translate("MainWindow", "Solver"))
        self.solverStandard.setText(_translate("MainWindow", "Standard"))
        self.solverAdvanced.setText(_translate("MainWindow", "Advanced"))
        self.solverHeuristic.setItemText(0, _translate("MainWindow", "Pattern database 7-8"))
        self.solverHeuristic.setItemText(1, _translate("MainWindow", "Pattern database 6-6-3 + Walking distance"))
        self.solverHeuristic.setItemText(2, _translate("MainWindow", "Pattern database 5-5-5 + Walking distance"))
        self.solverHeuristic.setItemText(3, _translate("MainWindow", "Walking dist + Manhattan dist w/ linear conflict"))
        self.solverHeuristic.setItemText(4, _translate("MainWindow", "Walking distance"))
        self.solverHeuristic.setItemText(5, _translate("MainWindow", "Manhattan distance with Linear Conflict"))
        self.solverHeuristic.setItemText(6, _translate("MainWindow", "Manhattan distance"))
        self.solverHeuristic.setCurrentIndex(0)
        self.solverSearchNow.setText(_translate("MainWindow", "Find Optimal Solution"))
        self.solverEstimate.setText(_translate("MainWindow", "Estimate:"))
        self.solverResult.setText(_translate("MainWindow", "Result:"))
        self.solverNodes.setText(_translate("MainWindow", "Nodes:"))
        self.solverTime.setText(_translate("MainWindow", "Time:"))
